name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore CutThePause.sln

      - name: Build
        run: dotnet build CutThePause.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test CutThePause.sln --configuration Release --no-build
